Repository kevinthedang/discord-ollama, pull requests merged in 2024-11, with the labels that each got.

#134 Updated Guides and Goals
  README.md
  docs/commands-guide.md
  docs/events-guide.md
Labels: documentation

#136 Roll NPM Dependencies Forward
  docker-compose.yml
  package-lock.json
  package.json
  src/utils/messageEmbed.ts
  src/utils/messageNormal.ts
Labels: dependency

#137 Pull/Switch Model Commands Fix
  docker-compose.yml
  package-lock.json
  package.json
  src/commands/capacity.ts
  src/commands/cleanUserChannelHistory.ts
  src/commands/disable.ts
  src/commands/messageStream.ts
  src/commands/messageStyle.ts
  src/commands/pullModel.ts
  src/commands/shutoff.ts
  src/commands/switchModel.ts
  src/commands/threadCreate.ts
  src/commands/threadPrivateCreate.ts
  src/utils/configInterfaces.ts
  src/utils/handlers/chatHistoryHandler.ts
Labels: patch

#140 Code Owners File
  CODEOWNERS
Labels: documentation
