Repository kevinthedang/discord-ollama, pull requests merged in 2024-10, with the labels that each got.

#120 Code Coverage and Clean References
  .github/CONTRIBUTING.md
  .github/workflows/coverage.yml
  README.md
  src/client.ts
  src/commands/capacity.ts
  src/commands/cleanUserChannelHistory.ts
  src/commands/disable.ts
  src/commands/messageStream.ts
  src/commands/messageStyle.ts
  src/commands/threadCreate.ts
  src/commands/threadPrivateCreate.ts
  src/events/messageCreate.ts
  src/events/ready.ts
  src/keys.ts
  src/utils/configInterfaces.ts
  src/utils/env.ts
  src/utils/events.ts
  src/utils/index.ts
  src/utils/mentionClean.ts
  tests/commands.test.ts
  tests/events.test.ts
  tests/getEnvVar.test.ts
  tests/mentionClean.test.ts
  tests/queue.test.ts
  vitest.config.ts
Labels: dependencies, technical

#122 Environment Variable Validation
  docker-compose.yml
  package-lock.json
  package.json
  src/utils/env.ts
Labels: enhancement, dependency

#123 Remove CLIENT_UID Environment Variable
  .env.sample
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  docker-compose.yml
  docs/setup-discord-app.md
  docs/setup-local.md
  package-lock.json
  package.json
  src/events/messageCreate.ts
  src/keys.ts
  src/utils/events.ts
  src/utils/mentionClean.ts
  tests/mentionClean.test.ts
Labels: dependency, patch

#125 Pull Model Command
  src/client.ts
  src/commands/index.ts
  src/commands/pullModel.ts
  tests/commands.test.ts
  tests/events.test.ts
Labels: enhancement

#126 Switch Model Command
  .env.sample
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  README.md
  docker-compose.yml
  docs/setup-docker.md
  docs/setup-local.md
  package-lock.json
  package.json
  src/client.ts
  src/commands/index.ts
  src/commands/pullModel.ts
  src/commands/switchModel.ts
  src/events/messageCreate.ts
  src/keys.ts
  src/utils/configInterfaces.ts
  src/utils/events.ts
  src/utils/messageEmbed.ts
  src/utils/messageNormal.ts
  tests/commands.test.ts
Labels: enhancement, dependency

#130 Feature Set Documentation
  .github/CONTRIBUTING.md
  README.md
  docs/commands-guide.md
  docs/events-guide.md
Labels: documentation
