Repository kevinthedang/discord-ollama, pull requests merged in 2024-12, with the labels that each got.

#142 Pull and Switch Model Revised
  docker-compose.yml
  package-lock.json
  package.json
  src/commands/capacity.ts
  src/commands/cleanUserChannelHistory.ts
  src/commands/disable.ts
  src/commands/messageStream.ts
  src/commands/pullModel.ts
  src/commands/shutoff.ts
  src/commands/switchModel.ts
  src/commands/threadCreate.ts
  src/commands/threadPrivateCreate.ts
Labels: patch

#148 Streamlined Preferences Setup and Default Model
  .env.sample
  docker-compose.yml
  package-lock.json
  package.json
  src/client.ts
  src/events/messageCreate.ts
  src/keys.ts
  src/utils/events.ts
  src/utils/messageNormal.ts
Labels: enhancement

#149 Remove Message Style Command
  docker-compose.yml
  package-lock.json
  package.json
  src/commands/index.ts
  src/commands/messageStyle.ts
  src/events/messageCreate.ts
  src/utils/configInterfaces.ts
  src/utils/index.ts
  src/utils/messageEmbed.ts
  tests/commands.test.ts
Labels: patch

#150 Delete Model Command
  docker-compose.yml
  package-lock.json
  package.json
  src/commands/deleteModel.ts
  src/commands/index.ts
  src/commands/pullModel.ts
  src/commands/shutoff.ts
  src/commands/switchModel.ts
  tests/commands.test.ts
Labels: enhancement

#133 Prepare Redis Environment
  .env.sample
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  CODEOWNERS
  Dockerfile
  README.md
  docker-compose.yml
  docs/commands-guide.md
  docs/events-guide.md
  docs/setup-docker.md
  package-lock.json
  package.json
  src/client.ts
  src/keys.ts
  src/utils/mentionClean.ts
  tests/commands.test.ts
Labels: enhancement, performance, dependency
