Repository kevinthedang/discord-ollama, pull requests merged in 2024-09, with the labels that each got.

#114 Script Cleaning and Fixes
  README.md
  docker-compose.yml
  docs/setup-docker.md
  nodemon.json
  package-lock.json
  package.json
  vitest.config.ts
Labels: documentation, technical

#115 Removed Channel Toggle Command
  docker-compose.yml
  package-lock.json
  package.json
  src/commands/channelToggle.ts
  src/commands/index.ts
  src/commands/threadCreate.ts
  src/commands/threadPrivateCreate.ts
  src/events/messageCreate.ts
  src/events/threadDelete.ts
  src/utils/configInterfaces.ts
  src/utils/handlers/chatHistoryHandler.ts
  tests/commands.test.ts
Labels: patch

#118 Message Attachment Image Recognition
  docker-compose.yml
  package-lock.json
  package.json
  src/client.ts
  src/events/messageCreate.ts
  src/utils/events.ts
  src/utils/handlers/bufferHandler.ts
  src/utils/index.ts
Labels: enhancement

#119 Combine Tech Debt Branches
  tests/commands.test.ts
Labels: dependencies, technical
