Repository kevinthedang/discord-ollama, pull requests merged in 2024-08, with the labels that each got.

#96 Run Build Pipelines
  .github/workflows/build.yml
Labels: CI/CD, fixes

#98 Fixed Incorrect Image Name
  .github/workflows/build.yml
Labels: CI/CD, fixes

#103 Removed GUILD_ID as an Environment Variable
  .env.sample
  src/keys.ts
Labels: dependencies

#105 Data Directory on Chat for Preferences
  docker-compose.yml
  package-lock.json
  package.json
  src/utils/handlers/configHandler.ts
Labels: patch

#107 Deploy Shield
  .github/workflows/release.yml
  README.md
Labels: documentation

#109 Remove references to GUILD_ID
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  docker-compose.yml
  docs/setup-local.md
Labels: dependencies

#111 Dependency Upgrade
  docker-compose.yml
  package-lock.json
  package.json
Labels: dependencies, patch
