Repository kevinthedang/discord-ollama, pull requests merged in 2024-06, with the labels that each got.

#58 Unit Testing for Code Coverage
  .github/workflows/build-test.yml
  .github/workflows/build.yml
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
  tests/commands.test.ts
  tests/events.test.ts
  tests/getEnvVar.test.ts
  tests/mentionClean.test.ts
  tests/queue.test.ts
  vitest.config.ts
Labels: tests

#64 CI Fixes and PR Tests
  .github/workflows/build.yml
  tests/commands.test.ts
  tests/events.test.ts
Labels: bug, enhancement

#68 Removed Ollama API Threads as an Option
  .github/workflows/build.yml
  .github/workflows/test.yml
  src/utils/streamHandler.ts
Labels: performance

#70 Infinite Message Length for Streamed Messages
  docker-compose.yml
  package-lock.json
  package.json
  src/utils/messageNormal.ts
Labels: enhancement

#72 Test Workflow PR Push Rules
  .github/workflows/test.yml
Labels: CI/CD

#74 Dependencies and Readme Updates
  .github/workflows/build.yml
  .github/workflows/test.yml
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/commands/messageStream.ts
  src/utils/messageEmbed.ts
  src/utils/messageNormal.ts
  src/utils/streamHandler.ts
  tsconfig.json
Labels: documentation, dependencies

#78 Issue and Pull Request Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation

#79 Guide and Documentation Overhaul
  README.md
  docs/setup-discord-app.md
  docs/setup-docker.md
  docs/setup-local.md
  imgs/tutorial/bot-in-server.png
  imgs/tutorial/client-id.png
  imgs/tutorial/create-app.png
  imgs/tutorial/created-app.png
  imgs/tutorial/discord-dev.png
  imgs/tutorial/invite.png
  imgs/tutorial/scope.png
  imgs/tutorial/server-invite-1.png
  imgs/tutorial/server-invite-2-auth.png
  imgs/tutorial/server-invite-3.png
  imgs/tutorial/token.png
Labels: documentation
