Repository kevinthedang/discord-ollama, pull requests merged in 2025-02, with the labels that each got.

#155 [Snyk] Upgrade discord.js from 14.16.3 to 14.17.3
  package-lock.json
  package.json
  src/commands/capacity.ts
  src/commands/cleanUserChannelHistory.ts
  src/commands/deleteModel.ts
  src/commands/disable.ts
  src/commands/messageStream.ts
  src/commands/shutoff.ts
  src/commands/switchModel.ts
  src/commands/threadCreate.ts
  src/commands/threadPrivateCreate.ts
  src/events/interactionCreate.ts
  src/events/messageCreate.ts
  src/events/ready.ts
  src/events/threadDelete.ts
  src/utils/env.ts
  src/utils/events.ts
  src/utils/handlers/chatHistoryHandler.ts
  src/utils/handlers/configHandler.ts
  src/utils/handlers/streamHandler.ts
  src/utils/messageNormal.ts
  tests/commands.test.ts
  tests/queue.test.ts
Labels: dependency

#158 Deprecated ephemeral field
  docker-compose.yml
  package-lock.json
  package.json
  src/commands/capacity.ts
  src/commands/cleanUserChannelHistory.ts
  src/commands/deleteModel.ts
  src/commands/disable.ts
  src/commands/messageStream.ts
  src/commands/pullModel.ts
  src/commands/shutoff.ts
  src/commands/threadCreate.ts
  src/commands/threadPrivateCreate.ts
Labels: bug, technical

#162 Server Deployment Scripts
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: CI/CD

#159 Upgrade Npm Packages
  package-lock.json
  package.json
  src/events/interactionCreate.ts
  src/events/messageCreate.ts
  src/events/ready.ts
  src/events/threadDelete.ts
  src/queues/queue.ts
Labels: dependency
